### ISSUE TITLE
When i use test the model in any resolution of images, i meet the following problem

### ISSUE THREAD

**Issue by TaoWangzj** [ZhendongWang6/Uformer#20]
This is my testing code:

import torch
import math
from model import  Uformer

def expand2square(timg, factor=16.0):
    _, _, h, w = timg.size()

    X = int(math.ceil(max(h, w) / float(factor)) * factor)

    img = torch.zeros(1, 3, X, X).type_as(timg)  # 3, h,w
    mask = torch.zeros(1, 1, X, X).type_as(timg)

    # print(img.size(),mask.size())
    # print((X - h)//2, (X - h)//2+h, (X - w)//2, (X - w)//2+w)
    img[:, :, ((X - h) // 2):((X - h) // 2 + h), ((X - w) // 2):((X - w) // 2 + w)] = timg
    mask[:, :, ((X - h) // 2):((X - h) // 2 + h), ((X - w) // 2):((X - w) // 2 + w)].fill_(1.0)

    return img, mask

x = torch.randn(1, 3, 128, 720)

rgb_noisy, mask = expand2square(x, factor=128)

print(rgb_noisy.size())
print(mask.size())
out = model(rgb_noisy, (1 - mask))
print(out.size())

I meet the following problem:

torch.Size([1, 3, 768, 768])
torch.Size([1, 1, 768, 768])
Traceback (most recent call last):
  File "/Users/Uformer-main/my_test.py", line 69, in <module>
    out = model(rgb_noisy, (1 - mask))
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/taowang/Downloads/框架学习/low_level_task/Uformer-main/model.py", line 1336, in forward
    conv0 = self.encoderlayer_0(y,mask=mask)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/Uformer-main/model.py", line 1044, in forward
    x = blk(x,mask)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/Uformer-main/model.py", line 695, in forward
    attn_mask = attn_mask or shift_attn_mask
RuntimeError: bool value of Tensor with more than one value is ambiguous

**Comment by ZhendongWang6** [comment]
We have just fixed the  masks, you can try again, hope a good practice!

**Comment by KB-co** [comment]
You choose Uformer...
===>Testing using weights:  ./weights/model_best.pth
  0%|                                                                                        | 0/8 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "test_in_any_resolution.py", line 105, in <module>
    rgb_restored = model_restoration(rgb_noisy, 1 - mask)
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/o2/model.py", line 1357, in forward
    deconv3 = self.decoderlayer_3(deconv3,mask=mask)
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/o2/model.py", line 1038, in forward
    x = blk(x,mask)
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/o2/model.py", line 707, in forward
    attn_windows = self.attn(x_windows, mask=attn_mask)  # nW*B, win_size*win_size, C
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/o2/model.py", line 348, in forward
    attn = (q @ k.transpose(-2, -1))
RuntimeError: CUDA out of memory. Tried to allocate 2.53 GiB (GPU 0; 23.70 GiB total capacity; 16.35 GiB already allocated; 1.94 GiB free; 20.44 GiB reserved in total by PyTorch)

The resolution of the test image is 2300×1700，batch size =1 has been set.

**Comment by KB-co** [comment]
The above error occurs when testing images of any resolution through the new code. Is this a common problem?

**Comment by KB-co** [comment]
You choose Uformer...
===>Testing using weights:  ./weights/model_best.pth
  0%|                                                                                        | 0/8 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "test_in_any_resolution.py", line 105, in <module>
    rgb_restored = model_restoration(rgb_noisy, 1 - mask)
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/o2/model.py", line 1357, in forward
    deconv3 = self.decoderlayer_3(deconv3,mask=mask)
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/o2/model.py", line 1038, in forward
    x = blk(x,mask)
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/o2/model.py", line 707, in forward
    attn_windows = self.attn(x_windows, mask=attn_mask)  # nW*B, win_size*win_size, C
  File "/home/1/anaconda3/envs/t1/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/1/o2/model.py", line 348, in forward
    attn = (q @ k.transpose(-2, -1))
RuntimeError: CUDA out of memory. Tried to allocate 2.53 GiB (GPU 0; 23.70 GiB total capacity; 16.35 GiB already allocated; 1.94 GiB free; 20.44 GiB reserved in total by PyTorch)

The above error was reported when the new code tested the pictures with a resolution of 2300 * 1700. Is this a common problem? How can we successfully test these large-resolution images? Thank you.
